
/*
	HummingBird Embedded Script Language

	Copyright by 2007-2011 HaangilSoft. All rights reserved.
	Jinhong Kim <Redperf@gmail.com>

	- VM Error Code Definitions.
*/



#define EC_0001_RNONSTR			"Error: read_vm_var_str"
#define EC_0002_WNONSTR			"Error: write_vm_var_str"
#define EC_0003_RNONF			"Error: read_vm_var_f"
#define EC_0004_WNONF			"Error: write_vm_var_f"
#define EC_0005_RNONI			"Error: read_vm_var_i"
#define EC_0006_WNONI			"Error: write_vm_var_i"
#define EC_0007_NONAOI			"Error: not array_open item."
#define EC_0008_ROCE			"Critical error: read_operand."
#define EC_0009_WOCE			"Critical error: write_operand."
#define EC_0010_TIERR			"Error: trans_integer"
#define EC_0011_PISERR			"Error: parse_IF_scope"
#define EC_0012_PWSERR			"Error: parse_WHILE_scope"
#define EC_0013_PPSERR			"Error: parse_PROC_scope"
#define EC_0014_EOPUSH			"Error: push_value"
#define EC_0015_EOPOP			"Error: pop_value"
#define EC_0016_EOPEEK			"Error: peek_value"
#define EC_0017_FAERR			"Error: STRUCT access error."
#define EC_0018_USCS			"Error: unstable state on vm_callstack found."
#define EC_0019_USCCS			"Error: unstable state on vm_calc_stack found."
#define EC_0020_ERS				"Error: READSTACK"
#define EC_0021_EPAW			"Error: POPAWAY"
#define EC_0022_EOPEEKF			"Error: peek_value_from: out of range."
#define EC_0023_ELDMD			"Error: LOADMODULE"
#define EC_0024_EGPRC			"Error: GETPROC"
#define EC_0025_ECPRC			"Error: CALLPROC"
#define EC_0026_EULDMD			"Error: UNLOADMODULE"
#define EC_0027_EGRET			"Error: GETRET"
#define EC_0027_EGHRET			"Error: GETHOSTRET"

#define EC_1000_VAD				"General validation error."
#define EC_1001_OUTIDX			"Error: Out of index."
#define EC_1002_CWTC			"Error: cannot write to constant."
#define EC_1003_WTNDV			"Error: There's wrong-type or not-defined variables used."
#define EC_1004_REDEFVAR		"Error: Redefinition of variable"
#define EC_1005_FNF				"File not found"
#define EC_1006_DENT			"#DEFINE Error: NULL token."
#define EC_1007_IEFNF			"#INCLUDE Error: file not found."
#define EC_1008_FMTE			"Error: STRUCT"
#define EC_1009_NSKUV			"Error: Unknown keyword/variable or wrong expression."
#define EC_1010_GPSERR			"Error: GETPORTSIZE"
#define EC_1011_NMOERR			"GETOFFSET error: no matching element."
#define EC_1012_GOERR			"Error: GETOFFSET"
#define EC_1013_PPOCV			"Error: PORTPACK: only a constant value is allowed."
#define EC_1014_MPERR			"Error: MAPPORT"
#define EC_1014_PPERR			"Error: PUTPORT"
#define EC_1015_RPERR			"Error: READPORT"
#define EC_1016_BERR			"Error: BYTE"
#define EC_1017_ESHRT			"Error: SHORT"
#define EC_1017_EWRD			"Error: WORD"
#define EC_1017_EDWRD			"Error: DWORD"
#define EC_1018_EINT			"Error: INT"
#define EC_1018_EINT64			"Error: INT64"
#define EC_1019_EFLT			"Error: FLOAT"
#define EC_1020_EDBL			"Error: DOUBLE"
#define EC_1021_ESTR			"Error: STRING"
#define EC_1022_EOIF			"Error: IF"
#define EC_1023_CONDERR			"Error: <condition> : Wrong comparison mark."
#define EC_1024_WERR			"Error: WHILE"
#define EC_1025_EOSLP			"Error: SLEEP"
#define EC_1026_EOOC			"Error: EVENT"
#define EC_1027_PLERR			"Error: Parameter list error."
#define EC_1028_PIWT			"Error: vm_pop_i: wrong type."
#define EC_1029_PFWT			"Error: vm_pop_f: wrong type."
#define EC_1030_PSWT			"Error: vm_pop_str: wrong type."
#define EC_1031_NSVAR			"Error: No such a variable"
#define EC_1032_ICT				"Error: Inconsistent type."
#define EC_1033_WPNUM			"Error: Wrong port number."
#define EC_1034_PNEMPT			"Error: The port is not empty."
#define EC_1035_WTNAF			"Wrong type error: not a STRUCT." 
#define EC_1036_MSTINT			"Error: GETOFFSET: The second parameter can be integer value."
#define EC_1037_MSTINTVAR		"Error: READPORT: The second parameter must be INT-CONST or INT-VAR."
#define EC_1038_FNF				"Error: Unknown function call."
#define EC_1039_UPRC			"Error: Unknown function name."
#define EC_1040_NREP			"Error: Not resolved entry point."

#define EC_2001_WOPR			"Critical error: Wrong operands."
#define EC_2002_CCLVAL			"Critical error: const cannot be l-value."
#define EC_2003_DBZ				"Critical error: Divide by zero."
#define EC_2004_TMISM			"Error: type mismatching."
#define EC_2005_WIP				"Error: Wrong Function IP."
